name: Publish
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: public
